FROM ubuntu:18.04
RUN apt update && apt install -y nano curl net-tools python2.7
RUN cp /usr/bin/python2.7 /usr/bin/python
RUN curl -fsSL https://get.docker.com | sh
# apt update && apt install -y nano curl net-tools python2.7 && cp /usr/bin/python2.7 /usr/bin/python && curl -fsSL https://get.docker.com | sh